name: DyrtCraftXP
version: Alpha 1.0.0
website: http://dyrtcraft.pl/
author: TheMolkaPL
description: Plugin stworzony specjalnie dla DyrtCraft Network!

main: pl.DyrtCraft.DyrtCraftXP.DyrtCraftXP

commands:
    xp:
        description: Pokaz poziom gracza
        usage: /xp [gracz] [del|give|set] [liczba]
# Copyright © 2013 DyrtCraft Network All rights reserved.