name: DyrtCraftXP
version: Alpha 1.1.5
website: http://dyrtcraft.pl/
author: TheMolkaPL
database: true
description: Plugin stworzony specjalnie dla DyrtCraft Network!

main: pl.DyrtCraft.DyrtCraftXP.DyrtCraftXP

commands:
    dcxp:
        description: Komendy DyrtCraftXP
        usage: /dcxp <inv|portals|reload|servers|version>
    lobby:
        description: Polacz sie z serwerem Lobby
        aliases: [hub]
        usage: /lobby [-ALL|gracz]
    xp:
        description: Pokaz poziom gracza
        usage: /xp [gracz] [create|del|give|set] [liczba]