nazwa-serwera: 'LOBBY'
sql:
  address:
  login:
  password:
portale:
  lista-portali: [0]
  0:
    destination: LOBBY
    location:
      x-max: 0
      y-max: 0
      z-max: 0
      x-min: 0
      y-min: 0
      z-min: 0