name: AltariaMC
version: Unknown
website: https://github.com/Altaria-Network/AltariaMC
author: TheMolkaPL
loadbefore: [WorldEdit]
database: true
description: Plugin stworzony specjalnie dla Altaria Network!

main: pl.dyrtcraft.xp.DyrtCraftXP

commands:
    dcxp:
        description: Komendy Altaria
        usage: /dcxp <inv|portals|reload|version>
    lobby:
        description: Wróc na serwer Lobby Altaria Network
        usage: /lobby [gracz|-ALL]