name: AltariaMC
version: Alpha 1.6.1
website: http://altariamc.eu/
author: TheMolkaPL
loadbefore: [WorldEdit]
database: true
description: Plugin stworzony specjalnie dla Altaria Network!

main: pl.dyrtcraft.xp.DyrtCraftXP

commands:
    dcxp:
        description: Komendy Altaria
        usage: /dcxp <inv|portals|reload|version>
    lobby:
        description: Wróc na serwer Lobby Altaria Network
        aliases: [hub]
        usage: /lobby [gracz|-ALL]